# Sorting the conferences and HSF trainings via "date" field

In [1]:
import json
import pandas as pd

## Sorting with pandas

In [3]:
confs = pd.read_json("_data/Conference.json")
confs.dropna(inplace=True)
confs

,title,location,date,url
1,Four top quark production at Run3 in the singl...,"APS Global Physics Summit (Denver, Colorado)",2026-05-19,https://cms-mgt-conferences.web.cern.ch/confer...
2,HEP Software Training with HSF/IRIS-HEP,"New Perspectives Meeting (Fermilab, Batavia, I...",2023-06-27,https://indico.fnal.gov/event/59506/contributi...
3,Trigger Development for Emerging Jet Analysis ...,"FNAL 56st Annual Users Meeting (Fermilab, Bata...",2023-06-28,https://indico.fnal.gov/event/59656/contributi...
4,Teaching Python the Sustainable Way: Lessons L...,PyHEP 2022 Workshop (Virtual),2022-09-12,https://indico.cern.ch/event/1150631/contribut...
5,PyROOT tutorial experience from SWC Workshop,12th ROOT Users' Workshop (Virtual),2022-05-10,https://indico.fnal.gov/event/23628/contributi...
6,New Trigger Studies for Emerging Jets at CMS E...,"PRIMS/JTM Conference (Humacao, Puerto Rico)",2022-04-09,/assets/pdfs/PRISM_BetterPoster_EMJ.pdf
7,Recent Progress in ML for Tracker DQM,DPF Conference (Virtual),2021-07-12,https://indico.cern.ch/event/1034469/contribut...
8,Machine Learning in DQM at CMS Experiment,"Physcon Conference (Rhode Island, USA)",2019-11-13,/assets/pdfs/Physcon_Poster.pdf
9,Machine Learning and Deep Neural Networks at C...,Physics symposium (University of Puerto Rico M...,2019-05-24,http://charma.uprm.edu/~malik/Undergrad_Summer...
10,Machine Learning in DQM at CMS Experiment,"PRISM/JTM Conference (Mayagüez, Puerto Rico)",2019-05-04,/assets/pdfs/ML4DQM_PRISM_2019_Talk.pdf
11,Using ML techniques for DQM at CMS,ML Hackathon (University of Puerto Rico Mayagüez),2019-04-25,https://indico.cern.ch/event/809812/contributi...
12,Machine Learning in DQM at CMS Experiment,FNAL 51st Annual Users Meeting and New Perspec...,2018-06-18,https://vms.fnal.gov/asset/detail?recid=1955984

In [4]:
confs.sort_values("date", ascending=False)

,title,location,date,url
1,Four top quark production at Run3 in the singl...,"APS Global Physics Summit (Denver, Colorado)",2026-05-19,https://cms-mgt-conferences.web.cern.ch/confer...
3,Trigger Development for Emerging Jet Analysis ...,"FNAL 56st Annual Users Meeting (Fermilab, Bata...",2023-06-28,https://indico.fnal.gov/event/59656/contributi...
2,HEP Software Training with HSF/IRIS-HEP,"New Perspectives Meeting (Fermilab, Batavia, I...",2023-06-27,https://indico.fnal.gov/event/59506/contributi...
4,Teaching Python the Sustainable Way: Lessons L...,PyHEP 2022 Workshop (Virtual),2022-09-12,https://indico.cern.ch/event/1150631/contribut...
5,PyROOT tutorial experience from SWC Workshop,12th ROOT Users' Workshop (Virtual),2022-05-10,https://indico.fnal.gov/event/23628/contributi...
6,New Trigger Studies for Emerging Jets at CMS E...,"PRIMS/JTM Conference (Humacao, Puerto Rico)",2022-04-09,/assets/pdfs/PRISM_BetterPoster_EMJ.pdf
7,Recent Progress in ML for Tracker DQM,DPF Conference (Virtual),2021-07-12,https://indico.cern.ch/event/1034469/contribut...
8,Machine Learning in DQM at CMS Experiment,"Physcon Conference (Rhode Island, USA)",2019-11-13,/assets/pdfs/Physcon_Poster.pdf
9,Machine Learning and Deep Neural Networks at C...,Physics symposium (University of Puerto Rico M...,2019-05-24,http://charma.uprm.edu/~malik/Undergrad_Summer...
10,Machine Learning in DQM at CMS Experiment,"PRISM/JTM Conference (Mayagüez, Puerto Rico)",2019-05-04,/assets/pdfs/ML4DQM_PRISM_2019_Talk.pdf
11,Using ML techniques for DQM at CMS,ML Hackathon (University of Puerto Rico Mayagüez),2019-04-25,https://indico.cern.ch/event/809812/contributi...
12,Machine Learning in DQM at CMS Experiment,FNAL 51st Annual Users Meeting and New Perspec...,2018-06-18,https://vms.fnal.gov/asset/detail?recid=1955984

In [5]:
result = confs.sort_values("date", ascending=False).to_json(
    orient="records", date_format="iso"
)
parsed = json.loads(result)
parsed

[{'title': 'Four top quark production at Run3 in the single-lepton final state with CMS',
  'location': 'APS Global Physics Summit (Denver, Colorado)',
  'date': '2026-05-19T00:00:00.000',
  'url': 'https://cms-mgt-conferences.web.cern.ch/conferences/pres_display.aspx?cid=4100&pid=32344'},
 {'title': 'Trigger Development for Emerging Jet Analysis (Poster)',
  'location': 'FNAL 56st Annual Users Meeting (Fermilab, Batavia, IL, USA)',
  'date': '2023-06-28T00:00:00.000',
  'url': 'https://indico.fnal.gov/event/59656/contributions/268969/'},
 {'title': 'HEP Software Training with HSF/IRIS-HEP',
  'location': 'New Perspectives Meeting (Fermilab, Batavia, IL, USA)',
  'date': '2023-06-27T00:00:00.000',
  'url': 'https://indico.fnal.gov/event/59506/contributions/269987/'},
 {'title': 'Teaching Python the Sustainable Way: Lessons Learned at HSF Training',
  'location': 'PyHEP 2022 Workshop (Virtual)',
  'date': '2022-09-12T00:00:00.000',
  'url': 'https://indico.cern.ch/event/1150631/contributions/5014278/'},
 {'title': 'PyROOT tutorial experience from SWC Workshop',
  'location': "12th ROOT Users' Workshop (Virtual)",
  'date': '2022-05-10T00:00:00.000',
  'url': 'https://indico.fnal.gov/event/23628/contributions/240752/'},
 {'title': 'New Trigger Studies for Emerging Jets at CMS Experiment',
  'location': 'PRIMS/JTM Conference (Humacao, Puerto Rico)',
  'date': '2022-04-09T00:00:00.000',
  'url': '/assets/pdfs/PRISM_BetterPoster_EMJ.pdf'},
 {'title': 'Recent Progress in ML for Tracker DQM',
  'location': 'DPF Conference (Virtual)',
  'date': '2021-07-12T00:00:00.000',
  'url': 'https://indico.cern.ch/event/1034469/contributions/4434622/'},
 {'title': 'Machine Learning in DQM at CMS Experiment',
  'location': 'Physcon Conference (Rhode Island, USA)',
  'date': '2019-11-13T00:00:00.000',
  'url': '/assets/pdfs/Physcon_Poster.pdf'},
 {'title': 'Machine Learning and Deep Neural Networks at CMS Experiment',
  'location': 'Physics symposium (University of Puerto Rico Mayagüez)',
  'date': '2019-05-24T00:00:00.000',
  'url': 'http://charma.uprm.edu/~malik/Undergrad_Summer_Symposium/2019/GF_2019.pdf'},
 {'title': 'Machine Learning in DQM at CMS Experiment',
  'location': 'PRISM/JTM Conference (Mayagüez, Puerto Rico)',
  'date': '2019-05-04T00:00:00.000',
  'url': '/assets/pdfs/ML4DQM_PRISM_2019_Talk.pdf'},
 {'title': 'Using ML techniques for DQM at CMS',
  'location': 'ML Hackathon (University of Puerto Rico Mayagüez)',
  'date': '2019-04-25T00:00:00.000',
  'url': 'https://indico.cern.ch/event/809812/contributions/3391219/'},
 {'title': 'Machine Learning in DQM at CMS Experiment',
  'location': 'FNAL 51st Annual Users Meeting and New Perspectives Meeting (Fermilab, Batavia, IL, USA) ',
  'date': '2018-06-18T00:00:00.000',
  'url': 'https://vms.fnal.gov/asset/detail?recid=1955984'}]

In [6]:
# writing to file called sorted_confs.json
json.dump(parsed, open("_data/sorted_confs.json", "w"), indent=4)

## Now for sorting the Trainings

In [ ]:
mentored = pd.read_json("_data/mentored.json")
mentored.drop_duplicates(keep=False, inplace=True)
mentored.sort_values("date", ascending=False, inplace=True)

In [ ]:
parsed = json.loads(mentored.to_json(orient="records", date_format="iso"))

json.dump(parsed, open("_data/sorted_mentored.json", "w"), indent=4)

# result = mentored.sort_values("date", ascending=False).to_json(
#     orient="records", date_format="iso"
# )
# # parsed = json.loads(result)
# # parsed

In [ ]:
# [{
#     "title": "HSF/IRIS-HEP Software Basics Training",
#     "location": "Virtual",
#     "date": "September 28-30, 2022",
#     "url": "https://indico.cern.ch/event/1190572/"
#   },
#   {
#     "title": "DANCE@Snowmass",
#     "location": "University of Washington, Seattle, USA",
#     "date": "July 19-23, 2022",
#     "url": "https://indico.cern.ch/event/1151329/"
#   },
#   {
#     "title": "Software Carpentry",
#     "location": "Virtual",
#     "date": "July 13-15, 2022",
#     "url": "https://www.raynamharris.com/2022-07-13-upr-online/"
#   },
#   {
#     "title": "Matplotlib Training",
#     "location": "Virtual",
#     "date": "April 21-22, 2022",
#     "url": "https://indico.cern.ch/event/1058838/"
#   },
#   {
#     "title": "Software Carpentry",
#     "location": "Virtual",
#     "date": "March 28-30, 2022",
#     "url": "https://indico.cern.ch/event/1112526/"
#   },
#   {
#     "title": "Data Analysis for Lab Research" ,
#     "location": "UPRM, Puerto Rico",
#     "date": "March 5, 2022",
#     "url": "https://indico.cern.ch/event/1132342/"
#   },
#   {
#     "title": "Software Carpentry",
#     "location": "Virtual",
#     "date": "Dec 13-15, 2021",
#     "url": "https://indico.cern.ch/event/1097111/"
#   },
#   {
#     "title": "HSF/IRISH-HEP Analysis Reproducibility",
#     "location": "Virtual",
#     "date": "Mar 24-28, 2025",
#     "url": "https://indico.cern.ch/event/1508102/timetable/"
#   },
#   {
#     "title": "",
#     "location": "",
#     "date": "",
#     "url": ""
#   },
#   {
#     "title": "",
#     "location": "",
#     "date": "",
#     "url": ""
#   }
# ]

## Creating the bibfile from inspire

In [ ]:
import requests

url = "https://inspirehep.net/api/literature?sort=mostrecent&size=90&page=1&q=a Guillermo.Fidalgo.1&format=bibtex"
# url = "https://inspirehep.net/api/literature?sort=mostrecent&size=1000&page=1&search_type=hep-author-publication&author=2054153_Guillermo Fidalgo"
# url = "https://inspirehep.net/api/literature/?sort=mostrecent&q=Guillermo%20Fidalgo&size=250&page=1&format=bibtex"
inspire = requests.get(url,).text
print(inspire)

<html><body><h1>502 Bad Gateway</h1>
The server returned an invalid or incomplete response.
</body></html>

In [47]:

# response = requests.get('https://inspirehep.net/api/literature?sort=mostrecent&size=250&page=1&q=Guillermo%20Fidalgo')
# url = response.json()['links']['bibtex']
# print(url)
# # print(response['links'])
# inspire = requests.get(url)

In [50]:
# test script from GPT
import requests
import time

# Base search endpoint
url = "https://inspirehep.net/api/literature"
query = "a Guillermo.Fidalgo.1"

params = {
    "sort": "mostrecent",
    "size": 50,  # Lower size ensures the backend won't give a 502
    "page": 1,
    "q": query
}

all_bibtex = ""

while True:
    print(f"Querying page {params['page']} for JSON index...")
    response = requests.get(url, params=params)
    
    if response.status_code != 200:
        print(f"Error {response.status_code} while fetching records.")
        break

    data = response.json()
    hits = data.get('hits', {}).get('hits', [])

    # Stop looping if no more search results return
    if not hits:
        print("Completed processing all pages.")
        break

    print(f"Extracting BibTeX for {len(hits)} papers on this page...")
    for hit in hits:
        # Extract the specialized BibTeX link generated by INSPIRE
        links = hit.get('links', {})
        bibtex_url = links.get('bibtex')
        
        if bibtex_url:
            try:
                # This fetches the raw pre-compiled string for the single record
                bib_response = requests.get(bibtex_url)
                if bib_response.status_code == 200:
                    all_bibtex += bib_response.text + "\n"
                else:
                    print(f" Failed to get BibTeX for record {hit.get('id')}")
            except Exception as e:
                print(f" Request failed for record {hit.get('id')}: {e}")
                
            # Respect the API speed limit (15 requests per 5 seconds)
            time.sleep(1) 

    # Advance to the next page of the search index
    params['page'] += 1

# Write everything out to a .bib file
if all_bibtex:
    with open("fidalgo_references.bib", "w", encoding="utf-8") as f:
        f.write(all_bibtex)
    print("\n Success! 'fidalgo_references.bib' has been created.")
else:
    print("\n No BibTeX entries were successfully retrieved.")

Querying page 1 for JSON index...
Extracting BibTeX for 50 papers on this page...
Querying page 2 for JSON index...
Extracting BibTeX for 50 papers on this page...
Querying page 3 for JSON index...
Extracting BibTeX for 11 papers on this page...
Querying page 4 for JSON index...
Completed processing all pages.

 Success! 'fidalgo_references.bib' has been created.

Making it into a script

In [55]:
%%writefile createbib.py 
# Ignore OLD code
# import requests
# url = "https://inspirehep.net/api/literature?sort=mostrecent&size=250&page=1&q=a Guillermo.Fidalgo.1&format=bibtex"
# inspire = requests.get(url).text


# New code (Super slow)

# test script from GPT
import requests
import time

# Base search endpoint
url = "https://inspirehep.net/api/literature"
query = "a Guillermo.Fidalgo.1"

params = {
    "sort": "mostrecent",
    "size": 50,  # Lower size ensures the backend won't give a 502
    "page": 1,
    "q": query
}

all_bibtex = ""

while True:
    print(f"Querying page {params['page']} for JSON index...")
    response = requests.get(url, params=params)
    
    if response.status_code != 200:
        print(f"Error {response.status_code} while fetching records.")
        break

    data = response.json()
    hits = data.get('hits', {}).get('hits', [])

    # Stop looping if no more search results return
    if not hits:
        print("Completed processing all pages.")
        break

    print(f"Extracting BibTeX for {len(hits)} papers on this page...")
    for hit in hits:
        # Extract the specialized BibTeX link generated by INSPIRE
        links = hit.get('links', {})
        bibtex_url = links.get('bibtex')
        
        if bibtex_url:
            try:
                # This fetches the raw pre-compiled string for the single record
                bib_response = requests.get(bibtex_url)
                if bib_response.status_code == 200:
                    all_bibtex += bib_response.text + "\n"
                else:
                    print(f" Failed to get BibTeX for record {hit.get('id')}")
            except Exception as e:
                print(f" Request failed for record {hit.get('id')}: {e}")
                
            # Respect the API speed limit (15 requests per 5 seconds)
            time.sleep(1) 

    # Advance to the next page of the search index
    params['page'] += 1


zenodo = r"""
@misc{alexander_moreno_briceno_2022_7115834,
  author       = {Alexander Moreno Briceño and Aman Goel and Guillermo Antonio Fidalgo Rodriguez},
  title        = {Teaching Python the Sustainable Way: Lessons Learned at HSF Training},
  month        = sep,
  year         = 2022,
  publisher    = {Zenodo},
  doi          = {10.5281/zenodo.7115834},
  url          = {https://doi.org/10.5281/zenodo.7115834}
}
"""

# Write everything out to a .bib file
if all_bibtex:
    with open("latex_files/bibfile.bib","w",encoding="utf-8") as f:
        f.write(all_bibtex)
        f.write(zenodo)
    print("\n Success! 'latex_files/bibfile.bib' has been created.")
else:
    print("\n No BibTeX entries were successfully retrieved.")

Overwriting createbib.py

In [56]:
! python createbib.py

Querying page 1 for JSON index...
Extracting BibTeX for 50 papers on this page...
Querying page 2 for JSON index...
Extracting BibTeX for 50 papers on this page...
Querying page 3 for JSON index...
Extracting BibTeX for 11 papers on this page...
Querying page 4 for JSON index...
Completed processing all pages.

 Success! 'latex_files/bibfile.bib' has been created.

## Making tests with Pandoc

Just run
```shell
pandoc -C _data/Publications.bib -t markdown_strict \
--csl american-physics-society.csl \
-o _includes/myPubs.md
```

In [59]:
! pandoc -C ./latex_files/bibfile.bib -t markdown_strict \
--csl ./latex_files/american-physics-society.csl \
 -o _includes/deleteME.md

[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math 4\ellγ, rendering as TeX:
  4\ellγ
        ^
  unexpected control sequence \ellγ
  expecting "%", "\\label", "\\tag", "\\nonumber", whitespace or "\\allowbreak"
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s_{\mathrm{NN}}}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s} = 13, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s_\mathrm{NN}}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}=13, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s} = 13, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}=13, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}=13, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}=13\,\text {Te}\hspace{-.08em}\text {V}, rendering as TeX
[WARNING] Could not convert TeX math \textrm{t}\overline{\textrm{t}}\textrm{W}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}=13, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}=13, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}=13, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}=13, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s} = 13\,\textrm{TeV}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}=13, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{\text{s}}=13.6, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{{s}_{\text{NN}}}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math 4\ellγ, rendering as TeX:
  4\ellγ
        ^
  unexpected control sequence \ellγ
  expecting "%", "\\label", "\\tag", "\\nonumber", whitespace or "\\allowbreak"
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s_{\mathrm{NN}}}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s} = 13, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s_\mathrm{NN}}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}=13, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s} = 13, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}=13, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}=13, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}=13\,\text {Te}\hspace{-.08em}\text {V}, rendering as TeX
[WARNING] Could not convert TeX math \textrm{t}\overline{\textrm{t}}\textrm{W}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}=13, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}=13, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}=13, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}=13, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s} = 13\,\textrm{TeV}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}=13, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{\text{s}}=13.6, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{{s}_{\text{NN}}}, rendering as TeX
[WARNING] Could not convert TeX math \sqrt{s}, rendering as TeX

In [ ]:
%%writefile Fixbib.py

def fixbib(data):
    for id,line in enumerate(data):
        if "$" in line : 
            line = line.replace("$","$$").replace(r"\_","_")
            print(f'Fixed line {id} with "{line}" ')
            data[id] = line
        if "{{s}_" in line:
            line = line.replace("{{s}_","{s_")
            print(f'Fixed line {id} with "{line}" ')
            data[id] = line
        # if "" in line:
        #     line = line.replace("</span>","")
        #     print(f'Fixed line {id} with "{line}" ')
        #     data[id] = line


with open("_includes/allPubs.md") as f:
    data = f.readlines()

fixbib(data)
with open("_includes/allPubs.md","w") as f:
    f.writelines(data)

# Making a pdf instead of markdown

In [60]:
! pandoc -C -s latex_files/bibfile.bib \
    --csl latex_files/american-physics-society.csl \
    -o latex_files/texfile.tex

In [ ]:
%%writefile Fixtex.py

text = r"""
\author{Guillermo Fidalgo}
\date{\today}
\title{Publication List}
\begin{document}
\maketitle
"""

characters = {
    "ψ": r"\psi",
    "ν": r"\nu",
    "γ": r"\gamma",
    "τ": r"\tau",
    "μ": r"\mu",
    "\u2006": r" ~ "
}
# nitems = len(characters)


def fixbib(data):
    for id, line in enumerate(data):
        if r"\author{}" in line:
            data[id : id + 5] = text
            print("added author, title, date and maketitle in lines", id, id + 5)

        for k, v in characters.items():
            if k in line:
                line1 = line.replace(k, v)
                print(f'Fixed line {id} from \n"{line:^30}"\n to \n"{line1:^30}" ')
                data[id] = line1
                line = line1


with open("latex_files/texfile.tex") as f:
    data = f.readlines()

fixbib(data)
with open("latex_files/texfile.tex", "w") as f:
    f.writelines(data)

In [ ]:
characters = {
    "ψ": r"\psi",
    "ν": r"\nu",
    "γ": r"\gamma",
    "τ": r"\tau",
    "μ": r"\mu",
    "\u2006": r" ~ ",
}

In [ ]:
characters

In [ ]:
for k, v in characters.items():
    if k in "the τ is not found":
        print(f"replacing line with {k}")

# Fixing one wierd entry

In [ ]:
Measurement of the ratio of the $\mathrm{B}_{c}^{+}\to{\mathrm{J}/\psi} \mu^{+}\nu_{\!\mu}$ and $\mathrm{B}_{c}^{+}\to{\mathrm{J}/\psi} \tau^{+}\nu_{\!\tau}$ branching fractions using three-prong  lepton decays


@article{CMS:2025jfx,
    author = "Chekhovsky, Vladimir and others",
    collaboration = "CMS",
    title = "{Measurement of the ratio of the B$_\mathrm{c}^+$$\to$ J/$ψ$$τ^+ν_τ$ and B$_\mathrm{c}^+$$\to$ J/$ψ$$μ^+ν_μ$ branching fractions using three-prong $τ$ lepton decays}",
    eprint = "2510.21559",
    archivePrefix = "arXiv",
    primaryClass = "hep-ex",
    reportNumber = "CMS-BPH-23-001, CERN-EP-2025-196",
    month = "10",
    year = "2025"
}

Measurement of the ratio of the $\mathrm{B}_{c}^{+}\to{\mathrm{J}/\psi} \mu^{+}\nu_{\!\mu}$ and $\mathrm{B}_{c}^{+}\to{\mathrm{J}/\psi} \tau^{+}\nu_{\!\tau}$ branching fractions using three-prong  lepton decays

# Now on to fixing the rest

In [64]:
! python Fixtex.py

# Quick local run

In [ ]:
! python createbib.py
! pandoc -C  --standalone latex_files/bibfile.bib \
        --csl latex_files/american-physics-society.csl \
            -o latex_files/texfile.tex
! python Fixtex.py